Compile with flag: --with-debug
Otherwise nginx-upstream-fair generates (incorrect?) errors::

  modules/nginx-upstream-fair/ngx_http_upstream_fair_module.c:
  In function 'ngx_http_upstream_fair_update_nreq':
  modules/nginx-upstream-fair/ngx_http_upstream_fair_module.c:649:41:
  error: variable 'total_nreq' set but not used
  [-Werror=unused-but-set-variable]
  modules/nginx-upstream-fair/ngx_http_upstream_fair_module.c:648:41:
  error: variable 'nreq' set but not used
  [-Werror=unused-but-set-variable]